//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminsite.model.timesheet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TimesheetResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TimesheetResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("adminsite.model.timesheet.TimesheetResources", typeof(TimesheetResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @comment.
        /// </summary>
        internal static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE_WORKLOAD.
        /// </summary>
        internal static string CreateWorkloadStoredProcedure {
            get {
                return ResourceManager.GetString("CreateWorkloadStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @day1.
        /// </summary>
        internal static string day1 {
            get {
                return ResourceManager.GetString("day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @day10.
        /// </summary>
        internal static string day10 {
            get {
                return ResourceManager.GetString("day10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @day11.
        /// </summary>
        internal static string day11 {
            get {
                return ResourceManager.GetString("day11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @day12.
        /// </summary>
        internal static string day12 {
            get {
                return ResourceManager.GetString("day12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @day13.
        /// </summary>
        internal static string day13 {
            get {
                return ResourceManager.GetString("day13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @day14.
        /// </summary>
        internal static string day14 {
            get {
                return ResourceManager.GetString("day14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @day15.
        /// </summary>
        internal static string day15 {
            get {
                return ResourceManager.GetString("day15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @day16.
        /// </summary>
        internal static string day16 {
            get {
                return ResourceManager.GetString("day16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @day2.
        /// </summary>
        internal static string day2 {
            get {
                return ResourceManager.GetString("day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @day3.
        /// </summary>
        internal static string day3 {
            get {
                return ResourceManager.GetString("day3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @day4.
        /// </summary>
        internal static string day4 {
            get {
                return ResourceManager.GetString("day4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @day5.
        /// </summary>
        internal static string day5 {
            get {
                return ResourceManager.GetString("day5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @day6.
        /// </summary>
        internal static string day6 {
            get {
                return ResourceManager.GetString("day6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @day7.
        /// </summary>
        internal static string day7 {
            get {
                return ResourceManager.GetString("day7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @day8.
        /// </summary>
        internal static string day8 {
            get {
                return ResourceManager.GetString("day8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @day9.
        /// </summary>
        internal static string day9 {
            get {
                return ResourceManager.GetString("day9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE_WORKLOAD.
        /// </summary>
        internal static string DeleteWorkloadStoredProcedure {
            get {
                return ResourceManager.GetString("DeleteWorkloadStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @employee.
        /// </summary>
        internal static string employee {
            get {
                return ResourceManager.GetString("employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @exitvalue.
        /// </summary>
        internal static string exitvalue {
            get {
                return ResourceManager.GetString("exitvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fk_accountcoursepermit.
        /// </summary>
        internal static string fk_accountcoursepermit {
            get {
                return ResourceManager.GetString("fk_accountcoursepermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fk_timesheet.
        /// </summary>
        internal static string fk_timesheet {
            get {
                return ResourceManager.GetString("fk_timesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_ALL_ACP_PER_OU.
        /// </summary>
        internal static string GetAllACPPerOUStoredProcedure {
            get {
                return ResourceManager.GetString("GetAllACPPerOUStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_ALL_TIMESHEET_BY_EMPLOYEE.
        /// </summary>
        internal static string GetAllTimesheetsByEmployeeStoredProcedure {
            get {
                return ResourceManager.GetString("GetAllTimesheetsByEmployeeStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_ALL_WORKLOADS.
        /// </summary>
        internal static string GetAllWorkloadsByTimesheet {
            get {
                return ResourceManager.GetString("GetAllWorkloadsByTimesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_TIMESHEET_BY_ID.
        /// </summary>
        internal static string GetTimesheetByIDStoredProcedure {
            get {
                return ResourceManager.GetString("GetTimesheetByIDStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_TIMESHEET_DATES.
        /// </summary>
        internal static string GetTimesheetDatesStoredProcedure {
            get {
                return ResourceManager.GetString("GetTimesheetDatesStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @id.
        /// </summary>
        internal static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @today.
        /// </summary>
        internal static string today {
            get {
                return ResourceManager.GetString("today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @unit.
        /// </summary>
        internal static string unit {
            get {
                return ResourceManager.GetString("unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE_TIMESHEET_STATUS.
        /// </summary>
        internal static string UpdateTimesheetStatusStoredProcedure {
            get {
                return ResourceManager.GetString("UpdateTimesheetStatusStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE_STATUS_WORKLOAD.
        /// </summary>
        internal static string UpdateWorkloadStatusStoredProcedure {
            get {
                return ResourceManager.GetString("UpdateWorkloadStatusStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE_WORKLOAD.
        /// </summary>
        internal static string UpdateWorkloadStoredProcedure {
            get {
                return ResourceManager.GetString("UpdateWorkloadStoredProcedure", resourceCulture);
            }
        }
    }
}
