//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminsite.model.hrm {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HRMResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HRMResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("adminsite.model.hrm.HRMResources", typeof(HRMResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE_EMPLOYEE.
        /// </summary>
        internal static string DeleteEmployeeStoredProcedure {
            get {
                return ResourceManager.GetString("DeleteEmployeeStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @enddate.
        /// </summary>
        internal static string enddate {
            get {
                return ResourceManager.GetString("enddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @exitvalue.
        /// </summary>
        internal static string exitvalue {
            get {
                return ResourceManager.GetString("exitvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_ALL_ORGANIZATIONAL_UNITS.
        /// </summary>
        internal static string GetAllOrganizationalUnitsStoredProcedure {
            get {
                return ResourceManager.GetString("GetAllOrganizationalUnitsStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_ALL_POSITIONS.
        /// </summary>
        internal static string GetAllPositionsStoredProcedure {
            get {
                return ResourceManager.GetString("GetAllPositionsStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_ALL_TIMESHEETS_HRM.
        /// </summary>
        internal static string GetAllTimesheetsHrmStoredProcedure {
            get {
                return ResourceManager.GetString("GetAllTimesheetsHrmStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_ALL_EMPLOYEES.
        /// </summary>
        internal static string GetEmployeesStoredProcedure {
            get {
                return ResourceManager.GetString("GetEmployeesStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_EMPLOYEES_WITH_OPEN_TIMESHEETS.
        /// </summary>
        internal static string GetEmployeesWithOpenTimesheetsStoredProcedure {
            get {
                return ResourceManager.GetString("GetEmployeesWithOpenTimesheetsStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_MANAGERS_WITH_PENDING_APPROVALS.
        /// </summary>
        internal static string GetManagersWithPendingApprovalsStoredProcedure1 {
            get {
                return ResourceManager.GetString("GetManagersWithPendingApprovalsStoredProcedure1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_OVERSEERS_WITH_PENDING_APPROVALS.
        /// </summary>
        internal static string GetOverseersWithPendingApprovalsStoredProcedure {
            get {
                return ResourceManager.GetString("GetOverseersWithPendingApprovalsStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @id.
        /// </summary>
        internal static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @idou.
        /// </summary>
        internal static string idou {
            get {
                return ResourceManager.GetString("idou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @idposition.
        /// </summary>
        internal static string idposition {
            get {
                return ResourceManager.GetString("idposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @initdate.
        /// </summary>
        internal static string initdate {
            get {
                return ResourceManager.GetString("initdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMOVE_SUPERVISOR_OF_ORGANIZATIONAL_UNIT.
        /// </summary>
        internal static string RemoveOrganizationalUnitOverseerStoredProcedure {
            get {
                return ResourceManager.GetString("RemoveOrganizationalUnitOverseerStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE_SUPERVISOR_OF_ORGANIZATIONAL_UNIT.
        /// </summary>
        internal static string UpdateOrganizationalUnitOverseerStoredProcedure {
            get {
                return ResourceManager.GetString("UpdateOrganizationalUnitOverseerStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE_POSITION_EMPLOYEE.
        /// </summary>
        internal static string UpdatePositionOrganizationalUnitStoredProcedure {
            get {
                return ResourceManager.GetString("UpdatePositionOrganizationalUnitStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @year.
        /// </summary>
        internal static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
    }
}
