//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminsite.model.acp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ACPResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ACPResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("adminsite.model.acp.ACPResources", typeof(ACPResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE_ACCOUNT_COURSE_PERMIT.
        /// </summary>
        internal static string CreateACPStoredProcedure {
            get {
                return ResourceManager.GetString("CreateACPStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE_COST_CENTER.
        /// </summary>
        internal static string CreateCostCenterStoredProcedure {
            get {
                return ResourceManager.GetString("CreateCostCenterStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE_ACCOUNT_COURSE_PERMIT.
        /// </summary>
        internal static string DeleteACPStoredProcedure {
            get {
                return ResourceManager.GetString("DeleteACPStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE_COST_CENTER.
        /// </summary>
        internal static string DeleteCostCenterStoredProcedure {
            get {
                return ResourceManager.GetString("DeleteCostCenterStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @enddate.
        /// </summary>
        internal static string enddate {
            get {
                return ResourceManager.GetString("enddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @exitvalue.
        /// </summary>
        internal static string exitvalue {
            get {
                return ResourceManager.GetString("exitvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fk_acp.
        /// </summary>
        internal static string fk_acp {
            get {
                return ResourceManager.GetString("fk_acp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fk_employee.
        /// </summary>
        internal static string fk_employee {
            get {
                return ResourceManager.GetString("fk_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fk_ou.
        /// </summary>
        internal static string fk_ou {
            get {
                return ResourceManager.GetString("fk_ou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_ACCOUNT_COURSE_PERMIT.
        /// </summary>
        internal static string GetAccountCoursePermitStoredProcedure {
            get {
                return ResourceManager.GetString("GetAccountCoursePermitStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_ALL_ACCOUNTS_COURSES_PERMITS.
        /// </summary>
        internal static string GetAllACPStoredProcedure {
            get {
                return ResourceManager.GetString("GetAllACPStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET_ALL_ORGANIZATIONAL_UNITS.
        /// </summary>
        internal static string GetOrganizationalUnitsCommand {
            get {
                return ResourceManager.GetString("GetOrganizationalUnitsCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @id.
        /// </summary>
        internal static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @initdate.
        /// </summary>
        internal static string initdate {
            get {
                return ResourceManager.GetString("initdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @type.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE_ACCOUNT_COURSE_PERMIT.
        /// </summary>
        internal static string UpdateAccountCoursePermitStoredProcedure {
            get {
                return ResourceManager.GetString("UpdateAccountCoursePermitStoredProcedure", resourceCulture);
            }
        }
    }
}
